correct package lock
open-olive/vscode-loop-development-kit pull request #42
Opened 2022-04-26 20:25 UTC by aleciberg-olive

2022-04-26 20:45 UTC, jonathan-olive approved these changes

2022-04-27 14:33 UTC, ulricesparra-oliveai requested changes
Make sure to double check that running `npm i` in the other two projects doesn't also result in changes to `package-lock.json` just in case

2022-04-27 16:08 UTC, aleciberg-olive commented on create-loop/package.json
> +  "version": "1.2.1",
Whoops per Github's checks I have to bump the version for create loop

2022-04-27 16:13 UTC, aleciberg-olive commented on create-loop/package.json
> +  "version": "1.2.1",
and turns out for vscode ext as well

2022-04-27 17:51 UTC, merged