Helps 4366 add search aptitude to vs code/npx
open-olive/vscode-loop-development-kit pull request #45
Opened 2022-05-02 21:09 UTC by aleciberg-olive

2022-05-06 17:15 UTC, ulricesparra-oliveai requested changes

2022-05-06 17:15 UTC, ulricesparra-oliveai commented on loop-templates/templates/src/aptitudes/index.ts.squirrelly
> +  runSearchExample,
The naming convention here is different than the rest so it seems out of place. Can we change it to `searchExample` and `searchExample.run()`?

2022-05-06 17:15 UTC, ulricesparra-oliveai commented on loop-templates/templates/src/whispers/SearchWhisper.test.ts.squirrelly
> +describe('Clipboard Whisper', () => {
```suggestion
describe('Search Whisper', () => {
```

2022-05-11 19:33 UTC, jonathan-olive commented
It seems like those webpack files Ryan added for his PR are going to be deleted when merged? Might want to double check it and the flowchart as well

2022-05-23 19:08 UTC, jonathan-olive commented
Small updates:
`loop-templates/templates/src` needs an update to `index.test.ts.squirrelly`
'vscode-extension` needs a `ChangeLog.md` i'd hope it works nicely w/ git when we want to merge it later

2022-05-23 22:19 UTC, merged